include:
  - project: cs/gitlabci-templates
    file: /build-image-using-kaniko.yml

variables:
  FF_USE_FASTZIP: 'true'
  ARTIFACT_COMPRESSION_LEVEL: 'fast'
  CACHE_COMPRESSION_LEVEL: 'fast'
  KUBERNETES_MEMORY_REQUEST: 4Gi
  KUBERNETES_MEMORY_LIMIT: 8Gi
  KUBERNETES_CPU_REQUEST: 1
  KUBERNETES_CPU_LIMIT: 4

default:
  interruptible: true

stages:
  - lint
  - build

cache:
  key:
    files:
      - package-lock.json
  paths:
    - .npm/

eslint:
  image: node:16-alpine
  stage: lint
  before_script:
    - npm ci
  script:
    - npm run lint

build-img-prod:
  extends: .build-image-using-kaniko
  stage: build
  variables:
    CI_PROJECT_DIR: /builds/nse/sscx-portal
    CI_REGISTRY_IMAGE: $CI_REGISTRY/nse/sscx-portal
    NEXT_PUBLIC_ENVIRONMENT: prod
    NEXT_PUBLIC_GTM_ID: $GTM_ID
    NEXT_PUBLIC_NEXUS_TOKEN: $NEXUS_TOKEN
    NEXT_PUBLIC_SENTRY_DSN: $SENTRY_DSN
    REGISTRY_IMAGE_TAG: latest
    SENTRY_AUTH_TOKEN: $SENTRY_AUTH_TOKEN
    SITE_URL: https://bbp.epfl.ch/sscx-portal/
    KANIKO_EXTRA_ARGS: >
      --build-arg=NEXT_PUBLIC_ENVIRONMENT
      --build-arg=NEXT_PUBLIC_GTM_ID
      --build-arg=NEXT_PUBLIC_NEXUS_TOKEN
      --build-arg=NEXT_PUBLIC_SENTRY_DSN
      --build-arg=SENTRY_AUTH_TOKEN
      --build-arg=SITE_URL
  only:
    - develop

# build-img-dev:
#   extends: .build-image-using-kaniko
#   stage: build
#   variables:
#     NEXT_PUBLIC_GTM_ID: $GTM_ID
#     NEXT_PUBLIC_NEXUS_URL: https://staging.nexus.ocp.bbp.epfl.ch/v1
#     NEXT_PUBLIC_NEXUS_ORG: tests
#     NEXT_PUBLIC_NEXUS_PROJECT: integration
#     NEXT_PUBLIC_SENTRY_DSN: $SENTRY_DSN
#     NEXT_PUBLIC_ENVIRONMENT: dev
#     NEXT_PUBLIC_NEXUS_TOKEN: $STAGING_NEXUS_TOKEN
#     SENTRY_AUTH_TOKEN: $SENTRY_AUTH_TOKEN
#     CI_REGISTRY_IMAGE: $CI_REGISTRY/nse/sscx-portal
#     REGISTRY_IMAGE_TAG: dev
#     CI_PROJECT_DIR: /builds/nse/sscx-portal
#     KANIKO_EXTRA_ARGS: >
#       --build-arg=NEXT_PUBLIC_GTM_ID
#       --build-arg=NEXT_PUBLIC_NEXUS_URL
#       --build-arg=NEXT_PUBLIC_NEXUS_ORG
#       --build-arg=NEXT_PUBLIC_NEXUS_PROJECT
#       --build-arg=NEXT_PUBLIC_SENTRY_DSN
#       --build-arg=NEXT_PUBLIC_ENVIRONMENT
#       --build-arg=NEXT_PUBLIC_NEXUS_TOKEN
#       --build-arg=SENTRY_AUTH_TOKEN
#   only:
#     - develop
