export const electricalFeatures = {
  AHP_depth: "Relative voltage values at the first after-hyperpolarization",
  AHP_depth_abs: "Absolute voltage values at the first after-hyperpolarization",
  AP1_amp: "The relative height of the 1st action potential from spike onset",
  AP2_amp: "The relative height of the 2nd action potential from spike onset",
  AP_amplitude: "The relative heights of all the action potentials from spike onset",
  AP_duration_half_width: "Width of spike at half spike amplitude",
  APlast_amp: "The relative height of the last action potential from spike onset",
  ISI_CV: "The coefficient of variation of the ISIs",
  Spikecount: "Number of spikes in the trace, including outside of stimulus interval",
  burst_number: "The number of bursts",
  decay_time_constant_after_stim: "The decay time constant of the voltage right after the stimulus",
  inv_fifth_ISI: "1.0 over fifth ISI",
  inv_first_ISI: "1.0 over first ISI",
  inv_fourth_ISI: "1.0 over fourth ISI",
  inv_last_ISI: "1.0 over last ISI",
  inv_second_ISI: "1.0 over second ISI",
  inv_third_ISI: "1.0 over third ISI",
  inv_time_to_first_spike: "1.0 over time to first spike",
  maximum_voltage_from_voltagebase: "Difference between maximum voltage during stimulus and voltage base",
  mean_frequency: "The mean frequency of the firing rate",
  ohmic_input_resistance_vb_ssse: "The ratio between the voltage deflection",
  time_to_first_spike: "Time from the start of the stimulus to the maximum of the first peak",
  time_to_last_spike: "Time from the start of the stimulus to the maximum of the first peak",
  time_to_second_spike: "Time from the start of the stimulus to the maximum of the second peak",
  voltage_after_stim: "The mean voltage after the stimulus in",
  voltage_base: "The average voltage during the last 10% of time before the stimulus",
  voltage_deflection: "The voltage deflection between voltage base and steady-state voltage at stimend",
  voltage_deflection_begin: "The voltage deflection between voltage base and steady-state voltage soon after stimulation start",
  threshold_current: "The minimal amplitude (in nA) of a step current clamp injection that triggers an action potential",
  holding_current: "The current clamp amplitude (in nA) necessary to hold the cell at a predefined holding voltage",
};
